### PR TITLE
RepoId is confusing

### PR DESCRIPTION
**Pull request by jrw972**
Problem
-------

Usage of both RepoId and GUID_t causes confusion.

Solution
--------

Remove RepoId.

### CODE REVIEW

**Comment by mitza-oci** [comment]
Did you consider changing internal function names like `get_repo_id()`? It could be deferred to another PR.

**Comment by iguessthislldo** [comment]
> Did you consider changing internal function names like get_repo_id()?

That was my intention in the last part of: "... replace references to it with GUID_t, as well as any other appropriate adjustments that might be necessary.".

**Review by mitza-oci — APPROVED** [review]
Ready once CI issues are fixed https://github.com/OpenDDS/OpenDDS/actions/runs/3886409181/jobs/6631909838#step:14:3019 and one method is renamed

**Review by iguessthislldo — APPROVED** [review]

**Comment by mitza-oci** [comment]
Looks like there are still problems compiling the Wireshark dissector

**Pull request merged**
