### PR TITLE
Added code to show get_instance_handles() and lookup_instance()

### PR DESCRIPTION
**Pull request by Tom-Gigo**
These changes are only to tests/DCPS/PersistentDurability.  These changes do not cause the test to fail, they only help illustrate issue 1641.
  They show that, after persistent messages are read into a DataWriter, those messages do not appear correctly when using get_instance_handles() and get_key_value().  Nor can lookup_instance() find anything using known key values.

### CODE REVIEW

**Comment by mitza-oci** [comment]
Are all the changes here necessary to demonstrate the problem described in #1641?  If the overall test design needs to change, please also update the README in the same directory.  It seems like the next step would be to make the test fail when it encounters this problem.  Also remove nullptr so it will compile on all supported compilers.

**Comment by Tom-Gigo** [comment]
Yes, it will demonstrate the problem.
I’ll change nullptr back to NULL.
I was hesitant to make the test fail … just wanted to show problem.

**Comment by Tom-Gigo** [comment]
Did I use nullptr somewhere?
I thought perhaps I did out of habit, but I don’t see it in the files I checked in.

From: Tom Silva
Sent: Friday, May 8, 2020 4:31 PM
To: 'objectcomputing/OpenDDS' <reply@reply.github.com>
Subject: RE: [objectcomputing/OpenDDS] Added code to show get_instance_handles() and lookup_instance() (#1642)

Yes, it will demonstrate the problem.
I’ll change nullptr back to NULL.
I was hesitant to make the test fail … just wanted to show problem.

**Comment by Tom-Gigo** [comment]
Oh duh, nevermind … was on wrong branch

From: Tom Silva
Sent: Friday, May 8, 2020 4:41 PM
To: 'objectcomputing/OpenDDS' <reply@reply.github.com>
Subject: RE: [objectcomputing/OpenDDS] Added code to show get_instance_handles() and lookup_instance() (#1642)

Did I use nullptr somewhere?
I thought perhaps I did out of habit, but I don’t see it in the files I checked in.

From: Tom Silva
Sent: Friday, May 8, 2020 4:31 PM
To: 'objectcomputing/OpenDDS' <reply@reply.github.com>
Subject: RE: [objectcomputing/OpenDDS] Added code to show get_instance_handles() and lookup_instance() (#1642)

Yes, it will demonstrate the problem.
I’ll change nullptr back to NULL.
I was hesitant to make the test fail … just wanted to show problem.

**Comment by jrw972** [comment]
Closing this pull request as there are currently no plans for fixing persistence using the current architecture.  The issue that links to this pull request will stay open.

**Pull request closed without merging**
